package br.com.jiujitsu.manager.view;

import br.com.jiujitsu.manager.controller.database.AtletasDataManager;
import br.com.jiujitsu.manager.model.AtletaModel;
import br.com.jiujitsu.manager.model.AtletasTableModel;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ToolTipManager;

/**
 *
 * @author Andrey Luiz
 */
public class Main extends javax.swing.JFrame {
    
    private boolean editing;
    private AtletasTableModel model = new AtletasTableModel();
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.preConfigure();
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panelButtons = new javax.swing.JPanel();
        buttonIncluir = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        buttonSalvar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();
        tabPanels = new javax.swing.JTabbedPane();
        tabCadastro = new javax.swing.JPanel();
        tabCadastro1 = new javax.swing.JTabbedPane();
        panelPesquisa = new javax.swing.JPanel();
        checkTodos = new javax.swing.JCheckBox();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablePesquisa = new javax.swing.JTable();
        editPesquisa = new javax.swing.JTextField();
        comboCampoPesquisa = new javax.swing.JComboBox();
        checkActiveTyping = new javax.swing.JCheckBox();
        comboPesquisa = new javax.swing.JComboBox();
        buttonFiltrar = new javax.swing.JButton();
        panelCadastro = new javax.swing.JPanel();
        panelAtleta = new javax.swing.JPanel();
        labelCodigo = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelDataNasc = new javax.swing.JLabel();
        labelPeso = new javax.swing.JLabel();
        labelSexo = new javax.swing.JLabel();
        labelFaixa = new javax.swing.JLabel();
        labelCatIdade = new javax.swing.JLabel();
        labelCatPeso = new javax.swing.JLabel();
        editId = new javax.swing.JTextField();
        editNome = new javax.swing.JTextField();
        editPeso = new javax.swing.JSpinner();
        panelSexo = new javax.swing.JPanel();
        radioMasc = new javax.swing.JRadioButton();
        radioFem = new javax.swing.JRadioButton();
        comboFaixa = new javax.swing.JComboBox();
        comboCatIdade = new javax.swing.JComboBox();
        comboCatPeso = new javax.swing.JComboBox();
        labelKimono = new javax.swing.JLabel();
        panelKimono = new javax.swing.JPanel();
        checkboxKimono = new javax.swing.JCheckBox();
        radioLiso = new javax.swing.JRadioButton();
        radioTrancado = new javax.swing.JRadioButton();
        labelAcademia = new javax.swing.JLabel();
        editAcademia = new javax.swing.JTextField();
        editDataNasc = new com.toedter.calendar.JDateChooser();
        tabChaveamento = new javax.swing.JPanel();
        panelCombinacoes = new javax.swing.JPanel();
        panelAtletas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAtletas = new javax.swing.JTable();
        panelChaveamento_Comb = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableChaveamento_Comb = new javax.swing.JTable();
        buttonExcluir_Comb = new javax.swing.JButton();
        panelCombinacoes_Comb = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableCombinacoes_Comb = new javax.swing.JTable();
        buttonCancelar_Comb = new javax.swing.JButton();
        buttonCombinar = new javax.swing.JButton();
        buttonRight = new javax.swing.JButton();
        buttonLeft = new javax.swing.JButton();
        panelProcurar_Cha1 = new javax.swing.JPanel();
        buttonOK_Cha1 = new javax.swing.JButton();
        comboCategoria1 = new javax.swing.JComboBox();
        tabLutas = new javax.swing.JPanel();
        panelChaveamento = new javax.swing.JPanel();
        panelProcurar_Cha = new javax.swing.JPanel();
        buttonOK_Cha = new javax.swing.JButton();
        comboCategoria = new javax.swing.JComboBox();
        panelProxLutas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProxLutas = new javax.swing.JTable();
        buttonIniciarLuta = new javax.swing.JButton();
        panelVencedores = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableVencedores = new javax.swing.JTable();
        tabRelatorios = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jiu Jitsu Manager");
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        panelButtons.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonIncluir.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        buttonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jiujitsu/manager/view/imagens/plus.png"))); // NOI18N
        buttonIncluir.setText("Incluir");
        buttonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIncluirActionPerformed(evt);
            }
        });

        buttonEditar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        buttonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jiujitsu/manager/view/imagens/edit.png"))); // NOI18N
        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonSalvar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        buttonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jiujitsu/manager/view/imagens/save.png"))); // NOI18N
        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonCancelar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        buttonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jiujitsu/manager/view/imagens/block.png"))); // NOI18N
        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        buttonExcluir.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        buttonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jiujitsu/manager/view/imagens/delete.png"))); // NOI18N
        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonIncluir)
                    .addComponent(buttonEditar)
                    .addComponent(buttonSalvar)
                    .addComponent(buttonCancelar)
                    .addComponent(buttonExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPanels.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        checkTodos.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        checkTodos.setText("Exibir todos os registros");
        checkTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTodosActionPerformed(evt);
            }
        });

        tablePesquisa.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablePesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePesquisaMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tablePesquisa);

        editPesquisa.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        editPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editPesquisaKeyReleased(evt);
            }
        });

        comboCampoPesquisa.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        comboCampoPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID/Nome", "Peso", "Sexo", "Faixa", "Cat. Idade", "Cat. Peso", "Academia" }));
        comboCampoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCampoPesquisaActionPerformed(evt);
            }
        });

        checkActiveTyping.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        checkActiveTyping.setText("Active Typing");
        checkActiveTyping.setToolTipText("<html>\n<b>Marcado:</b> enquanto você digita, os dados vão sendo filtrados instantaneamente.<br />\n<b>Desmarcado:</b> os dados só serão filtrados quando você pressionar <b>|Enter|</b> ou clicar em <b>OK</b>.\n</html>");

        comboPesquisa.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        buttonFiltrar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buttonFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jiujitsu/manager/view/imagens/tick.png"))); // NOI18N
        buttonFiltrar.setText("OK");
        buttonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPesquisaLayout = new javax.swing.GroupLayout(panelPesquisa);
        panelPesquisa.setLayout(panelPesquisaLayout);
        panelPesquisaLayout.setHorizontalGroup(
            panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPesquisaLayout.createSequentialGroup()
                        .addComponent(checkTodos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelPesquisaLayout.createSequentialGroup()
                        .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6)
                            .addGroup(panelPesquisaLayout.createSequentialGroup()
                                .addComponent(editPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkActiveTyping, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                                .addComponent(buttonFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        panelPesquisaLayout.setVerticalGroup(
            panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkActiveTyping)
                    .addComponent(buttonFiltrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        tabCadastro1.addTab("Pesquisar", new javax.swing.ImageIcon(getClass().getResource("/br/com/jiujitsu/manager/view/imagens/search.png")), panelPesquisa); // NOI18N

        panelCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelAtleta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atleta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N
        panelAtleta.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        labelCodigo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelCodigo.setText("Código");

        labelNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelNome.setText("Nome");

        labelDataNasc.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelDataNasc.setText("Data de Nascimento");

        labelPeso.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelPeso.setText("Peso");

        labelSexo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelSexo.setText("Sexo");

        labelFaixa.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelFaixa.setText("Faixa");

        labelCatIdade.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelCatIdade.setText("Cat. Idade");

        labelCatPeso.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelCatPeso.setText("Cat. por Peso");

        editId.setEditable(false);
        editId.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        editNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        editNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        editPeso.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        editPeso.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(1.0f)));

        panelSexo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(radioMasc);
        radioMasc.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        radioMasc.setSelected(true);
        radioMasc.setText("Masculino");

        buttonGroup1.add(radioFem);
        radioFem.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        radioFem.setText("Feminino");

        javax.swing.GroupLayout panelSexoLayout = new javax.swing.GroupLayout(panelSexo);
        panelSexo.setLayout(panelSexoLayout);
        panelSexoLayout.setHorizontalGroup(
            panelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSexoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioMasc)
                    .addComponent(radioFem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSexoLayout.setVerticalGroup(
            panelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSexoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioMasc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioFem)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        comboFaixa.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        comboFaixa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Branca", "Cinza", "Amarela", "Laranja", "Verde", "Azul", "Roxa", "Marrom", "Preta", "Vermelha e Preta", "Vermelha" }));

        comboCatIdade.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        comboCatIdade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mirim", "Infantil A", "Infantil B", "Infanto Juvenil A", "Infanto Juvenil B", "Juvenil", "Adulto", "Master", "Senior", "Super Senior" }));

        comboCatPeso.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        comboCatPeso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Galo", "Pluma", "Pena", "Leve", "Médio", "Meio Pesado", "Pesado", "Super Pesado", "Pesadíssimo" }));

        labelKimono.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelKimono.setText("Kimono");

        panelKimono.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        checkboxKimono.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        checkboxKimono.setText("Com Kimono");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, radioLiso, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), checkboxKimono, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        buttonGroup2.add(radioLiso);
        radioLiso.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        radioLiso.setSelected(true);
        radioLiso.setText("Liso");

        buttonGroup2.add(radioTrancado);
        radioTrancado.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        radioTrancado.setText("Trançado");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, radioLiso, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), radioTrancado, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout panelKimonoLayout = new javax.swing.GroupLayout(panelKimono);
        panelKimono.setLayout(panelKimonoLayout);
        panelKimonoLayout.setHorizontalGroup(
            panelKimonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKimonoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKimonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKimonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(checkboxKimono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioLiso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(radioTrancado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelKimonoLayout.setVerticalGroup(
            panelKimonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKimonoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkboxKimono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioLiso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioTrancado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelAcademia.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelAcademia.setText("Academia");

        editAcademia.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelAtletaLayout = new javax.swing.GroupLayout(panelAtleta);
        panelAtleta.setLayout(panelAtletaLayout);
        panelAtletaLayout.setHorizontalGroup(
            panelAtletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtletaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAtletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAtletaLayout.createSequentialGroup()
                        .addGroup(panelAtletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelSexo)
                            .addComponent(panelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(panelAtletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editNome, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNome)
                            .addGroup(panelAtletaLayout.createSequentialGroup()
                                .addGroup(panelAtletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPeso)
                                    .addComponent(editPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelKimono)
                                    .addComponent(panelKimono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(panelAtletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboCatIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCatIdade)
                                    .addComponent(comboFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelFaixa)
                                    .addComponent(labelCatPeso)
                                    .addComponent(comboCatPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(labelAcademia)
                    .addComponent(editAcademia, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAtletaLayout.setVerticalGroup(
            panelAtletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtletaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAtletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigo)
                    .addComponent(labelNome))
                .addGap(2, 2, 2)
                .addGroup(panelAtletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAtletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataNasc)
                    .addComponent(labelPeso)
                    .addComponent(labelFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAtletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAtletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(editDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAtletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSexo)
                    .addComponent(labelKimono)
                    .addComponent(labelCatIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAtletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelKimono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAtletaLayout.createSequentialGroup()
                        .addComponent(comboCatIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelCatPeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCatPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(labelAcademia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editAcademia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCadastroLayout = new javax.swing.GroupLayout(panelCadastro);
        panelCadastro.setLayout(panelCadastroLayout);
        panelCadastroLayout.setHorizontalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(439, Short.MAX_VALUE))
        );
        panelCadastroLayout.setVerticalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        tabCadastro1.addTab("Detalhe", new javax.swing.ImageIcon(getClass().getResource("/br/com/jiujitsu/manager/view/imagens/document.png")), panelCadastro); // NOI18N

        javax.swing.GroupLayout tabCadastroLayout = new javax.swing.GroupLayout(tabCadastro);
        tabCadastro.setLayout(tabCadastroLayout);
        tabCadastroLayout.setHorizontalGroup(
            tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabCadastro1)
                .addContainerGap())
        );
        tabCadastroLayout.setVerticalGroup(
            tabCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabCadastro1)
                .addContainerGap())
        );

        tabPanels.addTab("Cadastro", tabCadastro);

        tabChaveamento.setMaximumSize(new java.awt.Dimension(1008, 670));
        tabChaveamento.setPreferredSize(new java.awt.Dimension(1008, 670));

        panelCombinacoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelAtletas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atletas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        tableAtletas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tableAtletas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableAtletas);

        javax.swing.GroupLayout panelAtletasLayout = new javax.swing.GroupLayout(panelAtletas);
        panelAtletas.setLayout(panelAtletasLayout);
        panelAtletasLayout.setHorizontalGroup(
            panelAtletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtletasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAtletasLayout.setVerticalGroup(
            panelAtletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtletasLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelChaveamento_Comb.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chaveamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        tableChaveamento_Comb.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tableChaveamento_Comb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tableChaveamento_Comb);

        buttonExcluir_Comb.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buttonExcluir_Comb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jiujitsu/manager/view/imagens/delete_1.png"))); // NOI18N
        buttonExcluir_Comb.setText("Excluir");

        javax.swing.GroupLayout panelChaveamento_CombLayout = new javax.swing.GroupLayout(panelChaveamento_Comb);
        panelChaveamento_Comb.setLayout(panelChaveamento_CombLayout);
        panelChaveamento_CombLayout.setHorizontalGroup(
            panelChaveamento_CombLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChaveamento_CombLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChaveamento_CombLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChaveamento_CombLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonExcluir_Comb))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelChaveamento_CombLayout.setVerticalGroup(
            panelChaveamento_CombLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChaveamento_CombLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExcluir_Comb)
                .addContainerGap())
        );

        panelCombinacoes_Comb.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Combinações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        tableCombinacoes_Comb.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tableCombinacoes_Comb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tableCombinacoes_Comb);

        buttonCancelar_Comb.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buttonCancelar_Comb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jiujitsu/manager/view/imagens/block_1.png"))); // NOI18N
        buttonCancelar_Comb.setText("Cancelar");

        buttonCombinar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buttonCombinar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jiujitsu/manager/view/imagens/tick.png"))); // NOI18N
        buttonCombinar.setText("Combinar");

        javax.swing.GroupLayout panelCombinacoes_CombLayout = new javax.swing.GroupLayout(panelCombinacoes_Comb);
        panelCombinacoes_Comb.setLayout(panelCombinacoes_CombLayout);
        panelCombinacoes_CombLayout.setHorizontalGroup(
            panelCombinacoes_CombLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCombinacoes_CombLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCombinacoes_CombLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCombinacoes_CombLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonCombinar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancelar_Comb)))
                .addContainerGap())
        );
        panelCombinacoes_CombLayout.setVerticalGroup(
            panelCombinacoes_CombLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCombinacoes_CombLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCombinacoes_CombLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelar_Comb)
                    .addComponent(buttonCombinar))
                .addContainerGap())
        );

        buttonRight.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buttonRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jiujitsu/manager/view/imagens/right.png"))); // NOI18N

        buttonLeft.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buttonLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jiujitsu/manager/view/imagens/left.png"))); // NOI18N

        panelProcurar_Cha1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Procurar por Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N
        panelProcurar_Cha1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        buttonOK_Cha1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buttonOK_Cha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jiujitsu/manager/view/imagens/tick.png"))); // NOI18N
        buttonOK_Cha1.setText("OK");

        comboCategoria1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelProcurar_Cha1Layout = new javax.swing.GroupLayout(panelProcurar_Cha1);
        panelProcurar_Cha1.setLayout(panelProcurar_Cha1Layout);
        panelProcurar_Cha1Layout.setHorizontalGroup(
            panelProcurar_Cha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcurar_Cha1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboCategoria1, 0, 192, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonOK_Cha1)
                .addContainerGap())
        );
        panelProcurar_Cha1Layout.setVerticalGroup(
            panelProcurar_Cha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcurar_Cha1Layout.createSequentialGroup()
                .addGroup(panelProcurar_Cha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProcurar_Cha1Layout.createSequentialGroup()
                        .addComponent(buttonOK_Cha1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(comboCategoria1))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelCombinacoesLayout = new javax.swing.GroupLayout(panelCombinacoes);
        panelCombinacoes.setLayout(panelCombinacoesLayout);
        panelCombinacoesLayout.setHorizontalGroup(
            panelCombinacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCombinacoesLayout.createSequentialGroup()
                .addGroup(panelCombinacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCombinacoesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelAtletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCombinacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCombinacoes_Comb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCombinacoesLayout.createSequentialGroup()
                        .addGroup(panelCombinacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCombinacoesLayout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(panelChaveamento_Comb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCombinacoesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelProcurar_Cha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCombinacoesLayout.setVerticalGroup(
            panelCombinacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCombinacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelProcurar_Cha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCombinacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAtletas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCombinacoesLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(buttonRight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLeft)
                        .addGap(0, 92, Short.MAX_VALUE))
                    .addComponent(panelCombinacoes_Comb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelChaveamento_Comb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tabChaveamentoLayout = new javax.swing.GroupLayout(tabChaveamento);
        tabChaveamento.setLayout(tabChaveamentoLayout);
        tabChaveamentoLayout.setHorizontalGroup(
            tabChaveamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabChaveamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCombinacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabChaveamentoLayout.setVerticalGroup(
            tabChaveamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabChaveamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCombinacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanels.addTab("Chaveamento", tabChaveamento);

        panelChaveamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelProcurar_Cha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Procurar por Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N
        panelProcurar_Cha.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        buttonOK_Cha.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        buttonOK_Cha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jiujitsu/manager/view/imagens/tick.png"))); // NOI18N
        buttonOK_Cha.setText("OK");

        comboCategoria.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelProcurar_ChaLayout = new javax.swing.GroupLayout(panelProcurar_Cha);
        panelProcurar_Cha.setLayout(panelProcurar_ChaLayout);
        panelProcurar_ChaLayout.setHorizontalGroup(
            panelProcurar_ChaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcurar_ChaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboCategoria, 0, 192, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonOK_Cha)
                .addContainerGap())
        );
        panelProcurar_ChaLayout.setVerticalGroup(
            panelProcurar_ChaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcurar_ChaLayout.createSequentialGroup()
                .addGroup(panelProcurar_ChaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProcurar_ChaLayout.createSequentialGroup()
                        .addComponent(buttonOK_Cha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(comboCategoria))
                .addContainerGap())
        );

        panelProxLutas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Próximas Lutas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N
        panelProxLutas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jScrollPane1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        tableProxLutas.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tableProxLutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableProxLutas);

        buttonIniciarLuta.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        buttonIniciarLuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jiujitsu/manager/view/imagens/forward.png"))); // NOI18N
        buttonIniciarLuta.setText("Iniciar Luta");

        javax.swing.GroupLayout panelProxLutasLayout = new javax.swing.GroupLayout(panelProxLutas);
        panelProxLutas.setLayout(panelProxLutasLayout);
        panelProxLutasLayout.setHorizontalGroup(
            panelProxLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProxLutasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProxLutasLayout.createSequentialGroup()
                .addContainerGap(398, Short.MAX_VALUE)
                .addComponent(buttonIniciarLuta)
                .addGap(388, 388, 388))
        );
        panelProxLutasLayout.setVerticalGroup(
            panelProxLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProxLutasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonIniciarLuta)
                .addContainerGap())
        );

        panelVencedores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vencedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        jScrollPane3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        tableVencedores.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tableVencedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tableVencedores);

        javax.swing.GroupLayout panelVencedoresLayout = new javax.swing.GroupLayout(panelVencedores);
        panelVencedores.setLayout(panelVencedoresLayout);
        panelVencedoresLayout.setHorizontalGroup(
            panelVencedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVencedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelVencedoresLayout.setVerticalGroup(
            panelVencedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVencedoresLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelChaveamentoLayout = new javax.swing.GroupLayout(panelChaveamento);
        panelChaveamento.setLayout(panelChaveamentoLayout);
        panelChaveamentoLayout.setHorizontalGroup(
            panelChaveamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChaveamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChaveamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelVencedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProxLutas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelChaveamentoLayout.createSequentialGroup()
                        .addComponent(panelProcurar_Cha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelChaveamentoLayout.setVerticalGroup(
            panelChaveamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChaveamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelProcurar_Cha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelProxLutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelVencedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tabLutasLayout = new javax.swing.GroupLayout(tabLutas);
        tabLutas.setLayout(tabLutasLayout);
        tabLutasLayout.setHorizontalGroup(
            tabLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabLutasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelChaveamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabLutasLayout.setVerticalGroup(
            tabLutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabLutasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelChaveamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanels.addTab("Lutas", tabLutas);

        javax.swing.GroupLayout tabRelatoriosLayout = new javax.swing.GroupLayout(tabRelatorios);
        tabRelatorios.setLayout(tabRelatoriosLayout);
        tabRelatoriosLayout.setHorizontalGroup(
            tabRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        tabRelatoriosLayout.setVerticalGroup(
            tabRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );

        tabPanels.addTab("Relatórios", tabRelatorios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPanels, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPanels, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIncluirActionPerformed
        editingProcedure(true, true, false, true, 1, editNome);
    }//GEN-LAST:event_buttonIncluirActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        if (tablePesquisa.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha, primeiro.", "Espere!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        AtletaModel atleta = model.getAtleta(tablePesquisa.getSelectedRow());
        
        editId.setText(String.valueOf(atleta.getId()));
        editNome.setText(atleta.getNome());
        editDataNasc.setDate(atleta.getData_nasc());
        editPeso.setValue(atleta.getPeso());
        radioMasc.setSelected(atleta.getSexo() == 'M');
        radioFem.setSelected(atleta.getSexo() == 'F');
        checkboxKimono.setSelected(atleta.isKimono());
        radioLiso.setSelected(atleta.getTipo_kimono() == 'L');
        radioTrancado.setSelected(atleta.getTipo_kimono() == 'T');
        editAcademia.setText(atleta.getAcademia());
        comboFaixa.setSelectedItem(atleta.getFaixa());
        comboCatIdade.setSelectedItem(atleta.getCategoria_idade());
        comboCatPeso.setSelectedItem(atleta.getCategoria_peso());
        
        editingProcedure(true, true, true, true, 1, editNome);
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        AtletasDataManager manager = new AtletasDataManager();
        
        if (editing) {
            
            AtletaModel example = new AtletaModel(Long.parseLong(editId.getText()));
            AtletaModel atleta = new AtletaModel();
            
            atleta.setNome(editNome.getText());
            atleta.setData_nasc(editDataNasc.getDate());
            atleta.setPeso(Double.valueOf(editPeso.getValue().toString()));
            atleta.setSexo(radioMasc.isSelected() ? 'M' : 'F');
            atleta.setKimono(checkboxKimono.isSelected());
            atleta.setTipo_kimono(radioLiso.isSelected() ? 'L' : 'T');
            atleta.setAcademia(editAcademia.getText());
            atleta.setFaixa(comboFaixa.getSelectedItem().toString());
            atleta.setCategoria_idade(comboCatIdade.getSelectedItem().toString());
            atleta.setCategoria_peso(comboCatPeso.getSelectedItem().toString());
            
            manager.update(example, atleta);
            
            editing = false;            
        } else {
            AtletaModel atleta = new AtletaModel(manager.getLastID() + 1);
        
            atleta.setNome(editNome.getText());
            atleta.setData_nasc(editDataNasc.getDate());
            atleta.setPeso(Double.valueOf(editPeso.getValue().toString()));
            atleta.setSexo(radioMasc.isSelected() ? 'M' : 'F');
            atleta.setKimono(checkboxKimono.isSelected());
            atleta.setTipo_kimono(radioLiso.isSelected() ? 'L' : 'T');
            atleta.setAcademia(editAcademia.getText());
            atleta.setFaixa(comboFaixa.getSelectedItem().toString());
            atleta.setCategoria_idade(comboCatIdade.getSelectedItem().toString());
            atleta.setCategoria_peso(comboCatPeso.getSelectedItem().toString());
            
            manager.store(atleta);
        }       
        
        JOptionPane.showMessageDialog(this, "Atleta '" + editNome.getText() + "' salvo.", "Informação", JOptionPane.INFORMATION_MESSAGE);
        
        filterTable(editPesquisa.getText());
        
        clearFieldsCadastro();
        
        editingProcedure(false, false, false, true, 0, editPesquisa);
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        clearFieldsCadastro();
        editingProcedure(false, false, false, true, 0, editPesquisa);
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        if (tablePesquisa.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha, primeiro!", "Ei...", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja mesmo excluir o atleta '" + editNome.getText() + "'?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (resposta == JOptionPane.YES_OPTION) {
            AtletasDataManager manager = new AtletasDataManager();            
            int linha = tablePesquisa.getSelectedRow();
            AtletaModel atleta = model.getAtleta(linha);
            String nome_atleta = atleta.getNome();
            manager.delete(atleta);
            model.removerAtleta(linha);
            JOptionPane.showMessageDialog(this, "Atleta '" + nome_atleta + "' foi excluido.", "Pronto", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonExcluirActionPerformed
    
    private void editPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editPesquisaKeyReleased
        if (checkActiveTyping.isSelected()) {
            filterTable(editPesquisa.getText());
        }
    }//GEN-LAST:event_editPesquisaKeyReleased

    private void checkTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTodosActionPerformed
        AtletasDataManager manager = new AtletasDataManager();
        model.addAll(manager.getAll());
    }//GEN-LAST:event_checkTodosActionPerformed

    private void comboCampoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCampoPesquisaActionPerformed
        evaluateCombosPesquisa();
    }//GEN-LAST:event_comboCampoPesquisaActionPerformed

    private void buttonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiltrarActionPerformed
        filterTable(editPesquisa.getText());
    }//GEN-LAST:event_buttonFiltrarActionPerformed

    private void tablePesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePesquisaMouseClicked
        if (evt.getClickCount() == 2) {
            buttonEditar.doClick();
        }
    }//GEN-LAST:event_tablePesquisaMouseClicked

    //<editor-fold defaultstate="collapsed" desc="Main Method">
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="Variables declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonCancelar_Comb;
    private javax.swing.JButton buttonCombinar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonExcluir_Comb;
    private javax.swing.JButton buttonFiltrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton buttonIncluir;
    private javax.swing.JButton buttonIniciarLuta;
    private javax.swing.JButton buttonLeft;
    private javax.swing.JButton buttonOK_Cha;
    private javax.swing.JButton buttonOK_Cha1;
    private javax.swing.JButton buttonRight;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JCheckBox checkActiveTyping;
    private javax.swing.JCheckBox checkTodos;
    private javax.swing.JCheckBox checkboxKimono;
    private javax.swing.JComboBox comboCampoPesquisa;
    private javax.swing.JComboBox comboCatIdade;
    private javax.swing.JComboBox comboCatPeso;
    private javax.swing.JComboBox comboCategoria;
    private javax.swing.JComboBox comboCategoria1;
    private javax.swing.JComboBox comboFaixa;
    private javax.swing.JComboBox comboPesquisa;
    private javax.swing.JTextField editAcademia;
    private com.toedter.calendar.JDateChooser editDataNasc;
    private javax.swing.JTextField editId;
    private javax.swing.JTextField editNome;
    private javax.swing.JSpinner editPeso;
    private javax.swing.JTextField editPesquisa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel labelAcademia;
    private javax.swing.JLabel labelCatIdade;
    private javax.swing.JLabel labelCatPeso;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelDataNasc;
    private javax.swing.JLabel labelFaixa;
    private javax.swing.JLabel labelKimono;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JPanel panelAtleta;
    private javax.swing.JPanel panelAtletas;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelCadastro;
    private javax.swing.JPanel panelChaveamento;
    private javax.swing.JPanel panelChaveamento_Comb;
    private javax.swing.JPanel panelCombinacoes;
    private javax.swing.JPanel panelCombinacoes_Comb;
    private javax.swing.JPanel panelKimono;
    private javax.swing.JPanel panelPesquisa;
    private javax.swing.JPanel panelProcurar_Cha;
    private javax.swing.JPanel panelProcurar_Cha1;
    private javax.swing.JPanel panelProxLutas;
    private javax.swing.JPanel panelSexo;
    private javax.swing.JPanel panelVencedores;
    private javax.swing.JRadioButton radioFem;
    private javax.swing.JRadioButton radioLiso;
    private javax.swing.JRadioButton radioMasc;
    private javax.swing.JRadioButton radioTrancado;
    private javax.swing.JPanel tabCadastro;
    private javax.swing.JTabbedPane tabCadastro1;
    private javax.swing.JPanel tabChaveamento;
    private javax.swing.JPanel tabLutas;
    private javax.swing.JTabbedPane tabPanels;
    private javax.swing.JPanel tabRelatorios;
    private javax.swing.JTable tableAtletas;
    private javax.swing.JTable tableChaveamento_Comb;
    private javax.swing.JTable tableCombinacoes_Comb;
    private javax.swing.JTable tablePesquisa;
    private javax.swing.JTable tableProxLutas;
    private javax.swing.JTable tableVencedores;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
    
    private void editingProcedure(boolean interf, boolean cadbtn, boolean editing, boolean changetab, int tabindex, Component toFocus) {
        changeInterfaceCadastro(interf);
        changeMainButtons(cadbtn);
        
        this.editing = editing;
        
        if (changetab) {
            tabCadastro1.setSelectedIndex(tabindex);
        }
        
        if (toFocus != null) {
            toFocus.requestFocus();
        }
    }
    
    private void preConfigure() {
        setLocationRelativeTo(null);
        
        evaluateCombosPesquisa();        
        tablePesquisa.setModel(model);
        
        editPesquisa.requestFocus();
        changeInterfaceCadastro(false);
        changeMainButtons(false);
        
        ToolTipManager.sharedInstance().setDismissDelay(60000);
    }
    
    private void changeInterfaceCadastro(boolean enabled) {
        panelAtleta.setEnabled(enabled);
        editNome.setEnabled(enabled);
        editDataNasc.setEnabled(enabled);
        editPeso.setEnabled(enabled);
        radioMasc.setEnabled(enabled);
        radioFem.setEnabled(enabled);
        checkboxKimono.setEnabled(enabled);
        radioLiso.setEnabled(enabled);
        radioTrancado.setEnabled(enabled);
        editAcademia.setEnabled(enabled);
        comboFaixa.setEnabled(enabled);
        comboCatIdade.setEnabled(enabled);
        comboCatPeso.setEnabled(enabled);
                
        tabPanels.setEnabled(!enabled);
    }
    
    private void changeMainButtons(boolean editing) {
        buttonIncluir.setEnabled(!editing);
        buttonEditar.setEnabled(!editing);
        buttonSalvar.setEnabled(editing);
        buttonCancelar.setEnabled(editing);
        buttonExcluir.setEnabled(!editing);
    }
    
    private void clearFieldsCadastro() {
        editId.setText(null);
        editNome.setText(null);
        editDataNasc.setDate(null);
        editPeso.setValue(0);
        radioMasc.setSelected(true);
        checkboxKimono.setSelected(false);
        radioLiso.setSelected(true);
        editAcademia.setText(null);
        comboFaixa.setSelectedIndex(0);
        comboCatIdade.setSelectedIndex(0);
        comboCatPeso.setSelectedIndex(0);
    }
    
    private void evaluateCombosPesquisa() {
        if (comboCampoPesquisa.getSelectedIndex() == 0 || comboCampoPesquisa.getSelectedIndex() == 1 || comboCampoPesquisa.getSelectedIndex() == 6) {
            editPesquisa.setEnabled(true);
            comboPesquisa.setEnabled(false);
            checkActiveTyping.setEnabled(true);
            comboPesquisa.setModel(new DefaultComboBoxModel());
        } else {
            if (comboCampoPesquisa.getSelectedIndex() == 2) {
                comboPesquisa.setModel(new DefaultComboBoxModel(new String[] {"Masculino", "Feminino"}));
            } else if (comboCampoPesquisa.getSelectedIndex() == 3) {
                comboPesquisa.setModel(new DefaultComboBoxModel(new String[] {"Branca", "Cinza", "Amarela", "Laranja", "Verde", "Azul", "Roxa", "Marrom", "Preta", "Vermelha e Preta", "Vermelha"}));
            } else if (comboCampoPesquisa.getSelectedIndex() == 4) {
                comboPesquisa.setModel(new DefaultComboBoxModel(new String[] {"Mirim", "Infantil A", "Infantil B", "Infanto Juvenil A", "Infanto Juvenil B", "Juvenil", "Adulto", "Master", "Senior", "Super Senior"}));
            } else if (comboCampoPesquisa.getSelectedIndex() == 5) {
                comboPesquisa.setModel(new DefaultComboBoxModel(new String[] {"Galo", "Pluma", "Pena", "Leve", "Médio", "Meio Pesado", "Pesado", "Super Pesado", "Pesadíssimo"}));
            }
            editPesquisa.setEnabled(false);
            comboPesquisa.setEnabled(true);
            checkActiveTyping.setEnabled(false);
            checkActiveTyping.setSelected(false);
        }
    }
    
    private void filterTable(String text) {
        AtletasDataManager manager = new AtletasDataManager();
        List<AtletaModel> atletas = new ArrayList<>();

        switch (comboCampoPesquisa.getSelectedIndex()) {
            case 0:
                try {
                    long id = Long.parseLong(text);
                    atletas = manager.getByAttr("id", id);
                } catch (NumberFormatException except) {
                    String nome = text;
                    atletas = manager.getByAttr("nome", nome);
                }
                break;
            case 1:
                try {
                    double peso = Double.parseDouble(text);
                    atletas = manager.getByAttr("peso", peso);
                } catch (NumberFormatException except) {
                    editPesquisa.setText(null);
                }
                break;
            case 6:
                String academia = text;
                atletas = manager.getByAttr("academia", academia);
                break;
        }

        model.addAll(atletas);
    }
    
}